Repository UwUClub/EwECS, pull requests merged in 2023-10, with the labels that each got.

#1 Rt 75 resource manager template
  includes/EwECS/Asset/AssetHandler.hpp
  includes/EwECS/Asset/AssetManager.hpp
  includes/EwECS/Asset/CMakeLists.txt
  includes/EwECS/CMakeLists.txt
  includes/EwECS/EwECS.hpp
  src/Asset/AssetManager.cpp
  src/Asset/CMakeLists.txt
  src/CMakeLists.txt
Labels: enhancement

#2 Added interface for plugin
  includes/EwECS/Asset/AssetHandler.hpp
  includes/EwECS/Asset/AssetManager.hpp
  includes/EwECS/CMakeLists.txt
  includes/EwECS/IPlugin.hpp
Labels: enhancement

#5 Change rect pointer to ref and add usage of AssetsManager in RenderPlugin
  includes/EwECS/ConfigReader/ConfigReader.hpp
  includes/EwECS/SFMLDisplayClass/LoadedSprite.hpp
  includes/EwECS/SFMLDisplayClass/RenderPlugin.hpp
  includes/EwECS/SFMLDisplayClass/SFMLDisplayClass.hpp
  src/ConfigReader/ConfigReader.cpp
  src/SFMLDisplayClass/RenderPlugin.cpp
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
Labels: refactor

#4 Added Logger
  includes/EwECS/Logger.hpp
  src/CMakeLists.txt
  src/Logger.cpp
Labels: enhancement

#6 Rt 74 sound library plugin
  includes/EwECS/Asset/AssetHandler.hpp
  includes/EwECS/Asset/AssetManager.hpp
  includes/EwECS/Components/Components+Sounds.hpp
  includes/EwECS/Event/CMakeLists.txt
  includes/EwECS/Event/EventManager.hpp
  includes/EwECS/Event/MouseEvent.hpp
  includes/EwECS/Event/SoundEvent.hpp
  includes/EwECS/Event/WindowEvent.hpp
  includes/EwECS/EwECS.hpp
  includes/EwECS/SFMLDisplayClass/RenderPlugin.hpp
  includes/EwECS/SFMLDisplayClass/SFMLDisplayClass.hpp
  includes/EwECS/Sound/Sound.hpp
  includes/EwECS/World.hpp
  src/Asset/AssetManager.cpp
  src/ConfigReader/ConfigReader.cpp
  src/Event/CMakeLists.txt
  src/Event/EventManager.cpp
  src/Event/KeyboardEvent.cpp
  src/Event/MouseEvent.cpp
  src/Event/SoundEvent.cpp
  src/Event/WindowEvent.cpp
  src/JsonHandler/CMakeLists.txt
  src/JsonHandler/JsonHandler.cpp
  src/JsonHandler/JsonHandler.hpp
  src/SFMLDisplayClass/RenderPlugin.cpp
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
  src/Sound/Sound.cpp
  src/Utils.cpp
  src/World.cpp
Labels: enhancement

#7 Added Physic engine
  config/Gravity.json
  includes/EwECS/CMakeLists.txt
  includes/EwECS/ConfigReader/ConfigReader.hpp
  includes/EwECS/Physic/CMakeLists.txt
  includes/EwECS/Physic/HitBox.hpp
  includes/EwECS/Physic/PhysicPlugin.hpp
  includes/EwECS/Physic/Weight.hpp
  includes/EwECS/SFMLDisplayClass/RenderPlugin.hpp
  src/CMakeLists.txt
  src/ConfigReader/ConfigReader.cpp
  src/Physic/CMakeLists.txt
  src/Physic/PhysicPlugin.cpp
  src/SFMLDisplayClass/RenderPlugin.cpp
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
Labels: enhancement

#10 Fix compilation
  includes/EwECS/CMakeLists.txt
Labels: bug

#11 Fix compilation
  .github/workflows/ci.yaml
  CMakeLists.txt
  includes/EwECS/Asset/CMakeLists.txt
  includes/EwECS/CMakeLists.txt
  includes/EwECS/Components/CMakeLists.txt
  includes/EwECS/ConfigReader/CMakeLists.txt
  includes/EwECS/Event/CMakeLists.txt
  includes/EwECS/Physic/CMakeLists.txt
  includes/EwECS/SFMLDisplayClass/CMakeLists.txt
  includes/EwECS/Sound/CMakeLists.txt
  src/CMakeLists.txt
Labels: bug

#18 Rt 77 render library plugin
  includes/EwECS/SFMLDisplayClass/LoadedSprite.hpp
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
Labels: enhancement, refactor

#19 RT-86 create network plugin
  Dependencies.cmake
  includes/EwECS/Asset/AssetHandler.hpp
  includes/EwECS/CMakeLists.txt
  includes/EwECS/Network/CMakeLists.txt
  includes/EwECS/Network/ClientHandler.hpp
  includes/EwECS/Network/Connection.hpp
  includes/EwECS/Network/NetworkHandler.hpp
  includes/EwECS/Network/Packet.hpp
  includes/EwECS/Network/Serialization.hpp
  includes/EwECS/Network/ServerHandler.hpp
  includes/EwECS/Network/Values.hpp
  src/CMakeLists.txt
  src/Network/CMakeLists.txt
  src/Network/ClientHandler.cpp
  src/Network/NetworkHandler.cpp
  src/Network/ServerHandler.cpp
Labels: enhancement

#21 Change getInput system to get RELEASED key
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
Labels: enhancement

#23 Fix
  includes/EwECS/SFMLDisplayClass/SFMLDisplayClass.hpp
  includes/EwECS/SFMLDisplayClass/TextComponent.hpp
  src/Physic/PhysicPlugin.cpp
  src/SFMLDisplayClass/RenderPlugin.cpp
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
Labels: enhancement

#26 Fix create and killEntity
  src/World.cpp
Labels: bug

#27 Added path for installed program
  includes/EwECS/SFMLDisplayClass/TextComponent.hpp
  includes/EwECS/Utils.hpp
  src/ConfigReader/ConfigReader.cpp
  src/SFMLDisplayClass/SFMLDisplayClass.cpp
Labels: bug

#28 RT-92 Register Connection in server handler
  src/Network/ServerHandler.cpp
Labels: enhancement
